# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GroupReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scID', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scID', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('userPlaylists', models.ManyToManyField(to='iMusicMatch.Playlist')),
                ('userTracks', models.ManyToManyField(to='iMusicMatch.Track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='ownUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='ownUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='trackList',
            field=models.ManyToManyField(to='iMusicMatch.Track'),
        ),
        migrations.AddField(
            model_name='group',
            name='userList',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
